### PR TITLE
Latte completions: Macros starts with {

### PR DESCRIPTION
**Pull request by VojtaStanek**
Before, when you started typing {incl... it completes to {{include ...

### CODE REVIEW

**Comment by Michal-Mikolas** [comment]
This is not how to use these macros. It is designed to type "incl" (without bracket) and then press TAB, to include "{include #content}" code. It is much easier and more practical to use.

**Comment by VojtaStanek** [comment]
I'm using it like this: I start typing e.g. `{inc` (and Sublime makes it `{inc}`). Than "Oh, there is some help, yes `include` that is what I want." So I click on it. And then... 
`{{include #content}
}` 
(Which is not what I want)

I know that if someone is used to od it like you, it is easier and more practical, but for me not.
Or maybe there can be both completions one with `{` and one without. What do you think?

**Comment by solcik** [comment]
I think it should be as it is now.

If you (@Cactucs) need different behavior, You can easilly fork, change and put it into User folder.

Then Sublime will show both completions (or you can delete package) and use only your own.))

**Comment by radimsuckr** [comment]
@solcik In Sublime Text 3 this doesn't work. Completions appear only if you start typing {, but then this plugin completes it with another { so it's kind of useless.

**Comment by VojtaStanek** [comment]
That's what I sad. This is how it has to work. if you want to make it working you can use this package (my fork): https://github.com/Cactucs/Nette-package-for-Sublime-Text-2

**Comment by radimsuckr** [comment]
Correct me if I'm wrong, but I don't think that your fork allows writing Latte with starting by { character. Your fork enables completion of Latte macros but if you start typing with {, it still doubles it.

**Comment by VojtaStanek** [comment]
Sorry, i think it does what you want but not mater branch but patch-1: https://github.com/Cactucs/Nette-package-for-Sublime-Text-2/tree/patch-1

**Comment by radimsuckr** [comment]
Whoops, my bad. First time I downloaded master branch.

Patch-1 repairs typing with {, but autocomplete generates double }} at end of the closing macro.

```
{if $foo}
{/if}}
```

**Comment by VojtaStanek** [comment]
I thought it is at master also :D 
That's possible because I'm now using phpStorm... And I never tested it. 
So if you want to use it open pull reqest on my repo. (I think these lines needs fix: https://github.com/Cactucs/Nette-package-for-Sublime-Text-2/blob/patch-1/Latte.sublime-completions#L6-L38 )

Thanks

**Pull request closed without merging**
